"""
Fallback 2024 NFL season data + ESPN team ID mapping.
Used when live API calls fail or return no data.
"""

# ESPN internal team IDs (used for their public API endpoints)
ESPN_TEAM_IDS = {
    "ARI": 22, "ATL": 1,  "BAL": 33, "BUF": 2,  "CAR": 29,
    "CHI": 3,  "CIN": 4,  "CLE": 5,  "DAL": 6,  "DEN": 7,
    "DET": 8,  "GB":  9,  "HOU": 34, "IND": 11, "JAX": 30,
    "KC":  12, "LAC": 24, "LAR": 14, "LV":  13, "MIA": 15,
    "MIN": 16, "NE":  17, "NO":  18, "NYG": 19, "NYJ": 20,
    "PHI": 21, "PIT": 23, "SF":  25, "SEA": 26, "TB":  27,
    "TEN": 10, "WAS": 28,
}

FALLBACK_SCHEDULES = {
    "KC":  {"opp":"LV",  "home":True,  "stadium":"Arrowhead Stadium",         "surface":"Grass", "weather":"Clear 52°F 8mph",         "ou":44.5, "spread":-6.5},
    "BAL": {"opp":"PIT", "home":False, "stadium":"Acrisure Stadium",           "surface":"Grass", "weather":"Cold 38°F 12mph wind",     "ou":40.5, "spread":-3},
    "BUF": {"opp":"NE",  "home":True,  "stadium":"Highmark Stadium",           "surface":"Grass", "weather":"Cold 34°F 14mph wind",     "ou":42.5, "spread":-9},
    "CIN": {"opp":"CLE", "home":True,  "stadium":"Paycor Stadium",             "surface":"Turf",  "weather":"Dome",                     "ou":43.5, "spread":-3.5},
    "PHI": {"opp":"DAL", "home":False, "stadium":"AT&T Stadium",               "surface":"Turf",  "weather":"Dome",                     "ou":49.5, "spread":+1},
    "GB":  {"opp":"MIN", "home":True,  "stadium":"Lambeau Field",              "surface":"Grass", "weather":"Cold 29°F 10mph",          "ou":42.0, "spread":-2},
    "DAL": {"opp":"PHI", "home":True,  "stadium":"AT&T Stadium",               "surface":"Turf",  "weather":"Dome",                     "ou":49.5, "spread":-1},
    "SF":  {"opp":"LAR", "home":True,  "stadium":"Levi's Stadium",             "surface":"Grass", "weather":"Clear 62°F 5mph",          "ou":47.0, "spread":-5.5},
    "LAR": {"opp":"SF",  "home":False, "stadium":"Levi's Stadium",             "surface":"Grass", "weather":"Clear 62°F 5mph",          "ou":47.0, "spread":+5.5},
    "ATL": {"opp":"NO",  "home":True,  "stadium":"Mercedes-Benz Stadium",      "surface":"Turf",  "weather":"Dome",                     "ou":44.0, "spread":-4},
    "PIT": {"opp":"BAL", "home":True,  "stadium":"Acrisure Stadium",           "surface":"Grass", "weather":"Cold 38°F 12mph wind",     "ou":40.5, "spread":+3},
    "HOU": {"opp":"TEN", "home":True,  "stadium":"NRG Stadium",                "surface":"Turf",  "weather":"Dome",                     "ou":46.0, "spread":-7},
    "CAR": {"opp":"TB",  "home":False, "stadium":"Raymond James Stadium",      "surface":"Grass", "weather":"Partly Cloudy 74°F 6mph",  "ou":43.0, "spread":+10},
    "TEN": {"opp":"HOU", "home":False, "stadium":"NRG Stadium",                "surface":"Turf",  "weather":"Dome",                     "ou":46.0, "spread":+7},
    "IND": {"opp":"JAX", "home":False, "stadium":"EverBank Stadium",           "surface":"Grass", "weather":"Clear 71°F 8mph",          "ou":44.5, "spread":+2.5},
    "LV":  {"opp":"KC",  "home":False, "stadium":"Arrowhead Stadium",          "surface":"Grass", "weather":"Clear 52°F 8mph",          "ou":44.5, "spread":+6.5},
    "DET": {"opp":"CHI", "home":True,  "stadium":"Ford Field",                 "surface":"Turf",  "weather":"Dome",                     "ou":50.5, "spread":-10},
    "WAS": {"opp":"NYG", "home":True,  "stadium":"Northwest Stadium",          "surface":"Turf",  "weather":"Clear 58°F 7mph",          "ou":41.0, "spread":-6},
    "MIA": {"opp":"NYJ", "home":True,  "stadium":"Hard Rock Stadium",          "surface":"Grass", "weather":"Sunny 79°F 9mph",          "ou":43.0, "spread":-3},
    "LAC": {"opp":"DEN", "home":True,  "stadium":"SoFi Stadium",               "surface":"Turf",  "weather":"Dome",                     "ou":45.0, "spread":-4},
    "TB":  {"opp":"CAR", "home":True,  "stadium":"Raymond James Stadium",      "surface":"Grass", "weather":"Partly Cloudy 74°F 6mph",  "ou":43.0, "spread":-10},
    "CHI": {"opp":"DET", "home":False, "stadium":"Ford Field",                 "surface":"Turf",  "weather":"Dome",                     "ou":50.5, "spread":+10},
    "MIN": {"opp":"GB",  "home":False, "stadium":"Lambeau Field",              "surface":"Grass", "weather":"Cold 29°F 10mph",          "ou":42.0, "spread":+2},
    "SEA": {"opp":"ARI", "home":True,  "stadium":"Lumen Field",                "surface":"Turf",  "weather":"Rainy 52°F 11mph",         "ou":44.0, "spread":-4},
    "ARI": {"opp":"SEA", "home":False, "stadium":"Lumen Field",                "surface":"Turf",  "weather":"Rainy 52°F 11mph",         "ou":44.0, "spread":+4},
    "NYJ": {"opp":"MIA", "home":False, "stadium":"Hard Rock Stadium",          "surface":"Grass", "weather":"Sunny 79°F 9mph",          "ou":43.0, "spread":+3},
    "NYG": {"opp":"WAS", "home":False, "stadium":"Northwest Stadium",          "surface":"Turf",  "weather":"Clear 58°F 7mph",          "ou":41.0, "spread":+6},
    "JAX": {"opp":"IND", "home":True,  "stadium":"EverBank Stadium",           "surface":"Grass", "weather":"Clear 71°F 8mph",          "ou":44.5, "spread":-2.5},
    "NE":  {"opp":"BUF", "home":False, "stadium":"Highmark Stadium",           "surface":"Grass", "weather":"Cold 34°F 14mph wind",     "ou":42.5, "spread":+9},
    "CLE": {"opp":"CIN", "home":False, "stadium":"Paycor Stadium",             "surface":"Turf",  "weather":"Dome",                     "ou":43.5, "spread":+3.5},
    "DEN": {"opp":"LAC", "home":False, "stadium":"SoFi Stadium",               "surface":"Turf",  "weather":"Dome",                     "ou":45.0, "spread":+4},
    "NO":  {"opp":"ATL", "home":False, "stadium":"Mercedes-Benz Stadium",      "surface":"Turf",  "weather":"Dome",                     "ou":44.0, "spread":+4},
}

FALLBACK_DEF_RATINGS = {
    "LV":  {"pass_yd_pg":238,"rush_yd_pg":122,"pass_td_pg":1.80,"ppa":0.062,"pass_rank":28,"rush_rank":24},
    "BAL": {"pass_yd_pg":182,"rush_yd_pg":85, "pass_td_pg":1.08,"ppa":0.040,"pass_rank":1, "rush_rank":3},
    "BUF": {"pass_yd_pg":188,"rush_yd_pg":90, "pass_td_pg":1.22,"ppa":0.044,"pass_rank":3, "rush_rank":7},
    "CLE": {"pass_yd_pg":195,"rush_yd_pg":94, "pass_td_pg":1.32,"ppa":0.046,"pass_rank":6, "rush_rank":8},
    "PHI": {"pass_yd_pg":185,"rush_yd_pg":88, "pass_td_pg":1.10,"ppa":0.042,"pass_rank":3, "rush_rank":5},
    "DAL": {"pass_yd_pg":218,"rush_yd_pg":110,"pass_td_pg":1.60,"ppa":0.055,"pass_rank":18,"rush_rank":18},
    "MIN": {"pass_yd_pg":212,"rush_yd_pg":108,"pass_td_pg":1.50,"ppa":0.053,"pass_rank":15,"rush_rank":16},
    "SF":  {"pass_yd_pg":188,"rush_yd_pg":91, "pass_td_pg":1.20,"ppa":0.044,"pass_rank":4, "rush_rank":7},
    "LAR": {"pass_yd_pg":210,"rush_yd_pg":106,"pass_td_pg":1.45,"ppa":0.052,"pass_rank":14,"rush_rank":15},
    "GB":  {"pass_yd_pg":208,"rush_yd_pg":102,"pass_td_pg":1.42,"ppa":0.052,"pass_rank":13,"rush_rank":13},
    "ATL": {"pass_yd_pg":222,"rush_yd_pg":114,"pass_td_pg":1.62,"ppa":0.056,"pass_rank":20,"rush_rank":19},
    "NO":  {"pass_yd_pg":192,"rush_yd_pg":96, "pass_td_pg":1.30,"ppa":0.046,"pass_rank":5, "rush_rank":9},
    "TEN": {"pass_yd_pg":235,"rush_yd_pg":118,"pass_td_pg":1.75,"ppa":0.060,"pass_rank":26,"rush_rank":22},
    "HOU": {"pass_yd_pg":215,"rush_yd_pg":109,"pass_td_pg":1.55,"ppa":0.054,"pass_rank":17,"rush_rank":17},
    "IND": {"pass_yd_pg":220,"rush_yd_pg":112,"pass_td_pg":1.58,"ppa":0.055,"pass_rank":19,"rush_rank":18},
    "JAX": {"pass_yd_pg":228,"rush_yd_pg":116,"pass_td_pg":1.68,"ppa":0.057,"pass_rank":23,"rush_rank":21},
    "DET": {"pass_yd_pg":225,"rush_yd_pg":115,"pass_td_pg":1.65,"ppa":0.057,"pass_rank":22,"rush_rank":20},
    "CHI": {"pass_yd_pg":230,"rush_yd_pg":119,"pass_td_pg":1.70,"ppa":0.059,"pass_rank":25,"rush_rank":23},
    "WAS": {"pass_yd_pg":216,"rush_yd_pg":110,"pass_td_pg":1.56,"ppa":0.054,"pass_rank":17,"rush_rank":17},
    "NYG": {"pass_yd_pg":240,"rush_yd_pg":124,"pass_td_pg":1.85,"ppa":0.063,"pass_rank":29,"rush_rank":26},
    "MIA": {"pass_yd_pg":190,"rush_yd_pg":93, "pass_td_pg":1.28,"ppa":0.045,"pass_rank":4, "rush_rank":8},
    "NYJ": {"pass_yd_pg":185,"rush_yd_pg":89, "pass_td_pg":1.15,"ppa":0.043,"pass_rank":2, "rush_rank":6},
    "SEA": {"pass_yd_pg":205,"rush_yd_pg":101,"pass_td_pg":1.40,"ppa":0.051,"pass_rank":12,"rush_rank":13},
    "ARI": {"pass_yd_pg":232,"rush_yd_pg":120,"pass_td_pg":1.72,"ppa":0.060,"pass_rank":25,"rush_rank":24},
    "TB":  {"pass_yd_pg":200,"rush_yd_pg":100,"pass_td_pg":1.38,"ppa":0.049,"pass_rank":9, "rush_rank":11},
    "CAR": {"pass_yd_pg":245,"rush_yd_pg":128,"pass_td_pg":1.90,"ppa":0.064,"pass_rank":30,"rush_rank":28},
    "PIT": {"pass_yd_pg":198,"rush_yd_pg":98, "pass_td_pg":1.30,"ppa":0.048,"pass_rank":8, "rush_rank":12},
    "NE":  {"pass_yd_pg":202,"rush_yd_pg":104,"pass_td_pg":1.40,"ppa":0.050,"pass_rank":10,"rush_rank":14},
    "KC":  {"pass_yd_pg":184,"rush_yd_pg":87, "pass_td_pg":1.10,"ppa":0.042,"pass_rank":2, "rush_rank":4},
    "DEN": {"pass_yd_pg":194,"rush_yd_pg":95, "pass_td_pg":1.28,"ppa":0.046,"pass_rank":6, "rush_rank":9},
    "LAC": {"pass_yd_pg":198,"rush_yd_pg":99, "pass_td_pg":1.35,"ppa":0.048,"pass_rank":8, "rush_rank":11},
    "CIN": {"pass_yd_pg":196,"rush_yd_pg":97, "pass_td_pg":1.32,"ppa":0.047,"pass_rank":7, "rush_rank":10},
}

FALLBACK_INJURIES = {
    "Jalen Hurts":        {"status":"Q",  "note":"Knee",      "team":"PHI"},
    "Matthew Stafford":   {"status":"Q",  "note":"Hand",      "team":"LAR"},
    "Cooper Kupp":        {"status":"Q",  "note":"Hamstring", "team":"LAR"},
    "Christian McCaffrey":{"status":"Q",  "note":"Hamstring", "team":"SF"},
    "De'Von Achane":      {"status":"Q",  "note":"Ankle",     "team":"MIA"},
    "Isiah Pacheco":      {"status":"Q",  "note":"Ribs",      "team":"KC"},
    "AJ Brown":           {"status":"Q",  "note":"Foot",      "team":"PHI"},
    "T.J. Hockenson":     {"status":"D",  "note":"Back",      "team":"MIN"},
    "Rashee Rice":        {"status":"O",  "note":"Knee",      "team":"KC"},
    "Darren Waller":      {"status":"Q",  "note":"Hamstring", "team":"NYG"},
}

# Snap % by player name (season average)
FALLBACK_SNAPS = {
    "KC":  {"Patrick Mahomes":1.00,"Travis Kelce":0.82,"Isiah Pacheco":0.64,"Xavier Worthy":0.72,"Rashee Rice":0.0},
    "BAL": {"Lamar Jackson":1.00,"Mark Andrews":0.80,"Zay Flowers":0.82,"Isaiah Likely":0.62},
    "BUF": {"Josh Allen":1.00,"Stefon Diggs":0.86,"Keon Coleman":0.72},
    "CIN": {"Joe Burrow":1.00,"Ja'Marr Chase":0.88,"Tee Higgins":0.80},
    "PHI": {"Jalen Hurts":1.00,"AJ Brown":0.84,"Dallas Goedert":0.78,"Saquon Barkley":0.76},
    "GB":  {"Jordan Love":1.00,"Josh Jacobs":0.70,"Dontayvion Wicks":0.70},
    "DAL": {"Dak Prescott":1.00,"CeeDee Lamb":0.92,"Jake Ferguson":0.76},
    "SF":  {"Brock Purdy":1.00,"Christian McCaffrey":0.78,"George Kittle":0.82,"Brandon Aiyuk":0.84,"Deebo Samuel":0.78},
    "LAR": {"Matthew Stafford":1.00,"Cooper Kupp":0.76,"Puka Nacua":0.80},
    "ATL": {"Kirk Cousins":1.00,"Kyle Pitts":0.72},
    "PIT": {"Justin Fields":1.00,"George Pickens":0.84,"Pat Freiermuth":0.74},
    "HOU": {"CJ Stroud":1.00,"Stefon Diggs":0.86,"Joe Mixon":0.74},
    "DET": {"Jared Goff":1.00,"Amon-Ra St. Brown":0.90,"Jahmyr Gibbs":0.68,"David Montgomery":0.62},
    "WAS": {"Jayden Daniels":1.00,"Terry McLaurin":0.86,"Brian Robinson Jr":0.72},
    "MIA": {"Tua Tagovailoa":1.00,"Tyreek Hill":0.88,"Jaylen Waddle":0.85,"De'Von Achane":0.72},
    "MIN": {"Kirk Cousins":1.00,"Justin Jefferson":0.90,"Aaron Jones":0.68,"T.J. Hockenson":0.50},
    "SEA": {"Geno Smith":1.00,"DK Metcalf":0.87,"Tyler Lockett":0.80},
    "ARI": {"Kyler Murray":1.00,"Trey McBride":0.80},
    "TB":  {"Baker Mayfield":1.00,"Mike Evans":0.86,"Chris Godwin":0.82},
    "CAR": {"Bryce Young":1.00},
    "NYJ": {"Aaron Rodgers":1.00,"Garrett Wilson":0.88,"Breece Hall":0.70},
    "NYG": {"Daniel Jones":1.00,"Malik Nabers":0.86,"Darren Waller":0.58},
    "JAX": {"Trevor Lawrence":1.00,"Evan Engram":0.76,"Brian Thomas Jr":0.80},
    "IND": {"Anthony Richardson":1.00,"Jonathan Taylor":0.80,"Michael Pittman Jr":0.84},
    "NE":  {"Drake Maye":1.00},
    "CLE": {"Deshaun Watson":1.00,"David Njoku":0.78},
    "DEN": {"Bo Nix":1.00,"Javonte Williams":0.66,"Courtland Sutton":0.84},
    "NO":  {"Derek Carr":1.00,"Alvin Kamara":0.70},
    "LV":  {"Gardner Minshew":1.00,"Davante Adams":0.88},
    "LAC": {"Justin Herbert":1.00},
    "CHI": {"Caleb Williams":1.00,"DJ Moore":0.86,"Rome Odunze":0.76,"D'Andre Swift":0.72},
    "TEN": {"Will Levis":1.00,"Tony Pollard":0.66,"Tyler Boyd":0.72},
}
