"""
NFL Player Database — 2024 Season
All active offensive skill-position players with:
  - Season per-game averages
  - Standard deviations (for probability distribution)
  - L5 game form multiplier
  - Historical hit rates
"""

PLAYER_DB = {
    # ── QUARTERBACKS ──────────────────────────────────────────────────────────
    "mahomes": {
        "name": "Patrick Mahomes", "team": "KC", "pos": "QB", "num": "15", "tier": 1,
        "pass_yds": 299, "pass_tds": 2.1, "rush_yds": 22, "rush_att": 4.8,
        "completions": 25.4, "attempts": 36.1,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.74, "first_td": 0.22,
        "std": {"pass_yds": 52, "pass_tds": 0.90, "rush_yds": 14, "completions": 3.2, "attempts": 4.1},
        "l5": 1.04, "hr": {"pass_yds": 0.68, "pass_tds": 0.62, "rush_yds": 0.55},
    },
    "lamar": {
        "name": "Lamar Jackson", "team": "BAL", "pos": "QB", "num": "8", "tier": 1,
        "pass_yds": 248, "pass_tds": 1.9, "rush_yds": 62, "rush_att": 8.2,
        "completions": 20.1, "attempts": 29.8,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.88, "first_td": 0.28,
        "std": {"pass_yds": 55, "pass_tds": 0.85, "rush_yds": 22, "completions": 3.8, "attempts": 4.5},
        "l5": 1.07, "hr": {"pass_yds": 0.65, "pass_tds": 0.60, "rush_yds": 0.72},
    },
    "allen": {
        "name": "Josh Allen", "team": "BUF", "pos": "QB", "num": "17", "tier": 1,
        "pass_yds": 275, "pass_tds": 1.88, "rush_yds": 48, "rush_att": 7.1,
        "completions": 22.0, "attempts": 33.5,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.82, "first_td": 0.25,
        "std": {"pass_yds": 60, "pass_tds": 0.88, "rush_yds": 20, "completions": 3.6, "attempts": 4.7},
        "l5": 1.02, "hr": {"pass_yds": 0.67, "pass_tds": 0.61, "rush_yds": 0.63},
    },
    "burrow": {
        "name": "Joe Burrow", "team": "CIN", "pos": "QB", "num": "9", "tier": 1,
        "pass_yds": 282, "pass_tds": 1.95, "rush_yds": 12, "rush_att": 3.1,
        "completions": 22.8, "attempts": 34.2,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.71, "first_td": 0.19,
        "std": {"pass_yds": 58, "pass_tds": 0.92, "rush_yds": 10, "completions": 3.5, "attempts": 4.8},
        "l5": 0.97, "hr": {"pass_yds": 0.70, "pass_tds": 0.62, "rush_yds": 0.48},
    },
    "hurts": {
        "name": "Jalen Hurts", "team": "PHI", "pos": "QB", "num": "1", "tier": 1,
        "pass_yds": 255, "pass_tds": 1.72, "rush_yds": 58, "rush_att": 9.2,
        "completions": 20.8, "attempts": 31.4,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.85, "first_td": 0.27,
        "std": {"pass_yds": 56, "pass_tds": 0.87, "rush_yds": 22, "completions": 3.4, "attempts": 4.5},
        "l5": 1.01, "hr": {"pass_yds": 0.62, "pass_tds": 0.58, "rush_yds": 0.69},
    },
    "love": {
        "name": "Jordan Love", "team": "GB", "pos": "QB", "num": "10", "tier": 1,
        "pass_yds": 244, "pass_tds": 1.65, "rush_yds": 18, "rush_att": 3.8,
        "completions": 20.1, "attempts": 30.4,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.60, "first_td": 0.17,
        "std": {"pass_yds": 64, "pass_tds": 0.94, "rush_yds": 12, "completions": 3.9, "attempts": 4.6},
        "l5": 1.01, "hr": {"pass_yds": 0.60, "pass_tds": 0.55, "rush_yds": 0.50},
    },
    "dak": {
        "name": "Dak Prescott", "team": "DAL", "pos": "QB", "num": "4", "tier": 1,
        "pass_yds": 270, "pass_tds": 1.80, "rush_yds": 14, "rush_att": 3.2,
        "completions": 21.6, "attempts": 32.8,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.68, "first_td": 0.20,
        "std": {"pass_yds": 58, "pass_tds": 0.90, "rush_yds": 10, "completions": 3.3, "attempts": 4.4},
        "l5": 0.99, "hr": {"pass_yds": 0.65, "pass_tds": 0.60, "rush_yds": 0.50},
    },
    "brock": {
        "name": "Brock Purdy", "team": "SF", "pos": "QB", "num": "13", "tier": 2,
        "pass_yds": 258, "pass_tds": 1.72, "rush_yds": 8, "rush_att": 2.0,
        "completions": 21.4, "attempts": 31.8,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.64, "first_td": 0.18,
        "std": {"pass_yds": 60, "pass_tds": 0.88, "rush_yds": 8, "completions": 3.4, "attempts": 4.2},
        "l5": 1.02, "hr": {"pass_yds": 0.66, "pass_tds": 0.60, "rush_yds": 0.44},
    },
    "stafford": {
        "name": "Matthew Stafford", "team": "LAR", "pos": "QB", "num": "9", "tier": 2,
        "pass_yds": 258, "pass_tds": 1.72, "rush_yds": 6, "rush_att": 1.4,
        "completions": 21.4, "attempts": 31.8,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.62, "first_td": 0.17,
        "std": {"pass_yds": 62, "pass_tds": 0.91, "rush_yds": 8, "completions": 3.4, "attempts": 4.2},
        "l5": 0.99, "hr": {"pass_yds": 0.63, "pass_tds": 0.58, "rush_yds": 0.42},
    },
    "stroud": {
        "name": "CJ Stroud", "team": "HOU", "pos": "QB", "num": "7", "tier": 1,
        "pass_yds": 262, "pass_tds": 1.78, "rush_yds": 16, "rush_att": 3.5,
        "completions": 21.9, "attempts": 32.4,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.66, "first_td": 0.19,
        "std": {"pass_yds": 58, "pass_tds": 0.88, "rush_yds": 12, "completions": 3.5, "attempts": 4.4},
        "l5": 1.03, "hr": {"pass_yds": 0.66, "pass_tds": 0.60, "rush_yds": 0.52},
    },
    "tua": {
        "name": "Tua Tagovailoa", "team": "MIA", "pos": "QB", "num": "1", "tier": 1,
        "pass_yds": 268, "pass_tds": 1.82, "rush_yds": 10, "rush_att": 2.4,
        "completions": 22.2, "attempts": 33.0,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.64, "first_td": 0.18,
        "std": {"pass_yds": 56, "pass_tds": 0.89, "rush_yds": 9, "completions": 3.3, "attempts": 4.3},
        "l5": 1.00, "hr": {"pass_yds": 0.64, "pass_tds": 0.59, "rush_yds": 0.46},
    },
    "herbert": {
        "name": "Justin Herbert", "team": "LAC", "pos": "QB", "num": "10", "tier": 1,
        "pass_yds": 265, "pass_tds": 1.78, "rush_yds": 14, "rush_att": 3.0,
        "completions": 22.0, "attempts": 32.6,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.65, "first_td": 0.19,
        "std": {"pass_yds": 58, "pass_tds": 0.88, "rush_yds": 11, "completions": 3.4, "attempts": 4.4},
        "l5": 1.01, "hr": {"pass_yds": 0.65, "pass_tds": 0.59, "rush_yds": 0.49},
    },
    "goff": {
        "name": "Jared Goff", "team": "DET", "pos": "QB", "num": "16", "tier": 2,
        "pass_yds": 268, "pass_tds": 1.82, "rush_yds": 6, "rush_att": 1.5,
        "completions": 22.4, "attempts": 33.0,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.64, "first_td": 0.18,
        "std": {"pass_yds": 56, "pass_tds": 0.88, "rush_yds": 7, "completions": 3.3, "attempts": 4.3},
        "l5": 1.02, "hr": {"pass_yds": 0.66, "pass_tds": 0.60, "rush_yds": 0.40},
    },
    "mayfield": {
        "name": "Baker Mayfield", "team": "TB", "pos": "QB", "num": "6", "tier": 2,
        "pass_yds": 255, "pass_tds": 1.70, "rush_yds": 12, "rush_att": 2.8,
        "completions": 21.2, "attempts": 31.6,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.62, "first_td": 0.17,
        "std": {"pass_yds": 60, "pass_tds": 0.90, "rush_yds": 10, "completions": 3.5, "attempts": 4.5},
        "l5": 0.99, "hr": {"pass_yds": 0.62, "pass_tds": 0.57, "rush_yds": 0.48},
    },
    "cousins": {
        "name": "Kirk Cousins", "team": "ATL", "pos": "QB", "num": "8", "tier": 2,
        "pass_yds": 260, "pass_tds": 1.76, "rush_yds": 8, "rush_att": 1.8,
        "completions": 21.6, "attempts": 32.2,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.62, "first_td": 0.17,
        "std": {"pass_yds": 58, "pass_tds": 0.89, "rush_yds": 8, "completions": 3.4, "attempts": 4.4},
        "l5": 0.98, "hr": {"pass_yds": 0.63, "pass_tds": 0.58, "rush_yds": 0.42},
    },
    "fields": {
        "name": "Justin Fields", "team": "PIT", "pos": "QB", "num": "2", "tier": 2,
        "pass_yds": 224, "pass_tds": 1.42, "rush_yds": 66, "rush_att": 10.4,
        "completions": 18.8, "attempts": 28.6,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.86, "first_td": 0.28,
        "std": {"pass_yds": 68, "pass_tds": 0.95, "rush_yds": 24, "completions": 4.2, "attempts": 5.0},
        "l5": 1.00, "hr": {"pass_yds": 0.55, "pass_tds": 0.50, "rush_yds": 0.74},
    },
    "caleb": {
        "name": "Caleb Williams", "team": "CHI", "pos": "QB", "num": "18", "tier": 1,
        "pass_yds": 248, "pass_tds": 1.60, "rush_yds": 42, "rush_att": 7.8,
        "completions": 20.6, "attempts": 31.0,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.78, "first_td": 0.24,
        "std": {"pass_yds": 62, "pass_tds": 0.92, "rush_yds": 18, "completions": 3.8, "attempts": 4.6},
        "l5": 1.05, "hr": {"pass_yds": 0.60, "pass_tds": 0.55, "rush_yds": 0.68},
    },
    "jdaniels": {
        "name": "Jayden Daniels", "team": "WAS", "pos": "QB", "num": "5", "tier": 1,
        "pass_yds": 242, "pass_tds": 1.55, "rush_yds": 52, "rush_att": 8.4,
        "completions": 20.2, "attempts": 30.6,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.80, "first_td": 0.26,
        "std": {"pass_yds": 64, "pass_tds": 0.93, "rush_yds": 20, "completions": 3.9, "attempts": 4.7},
        "l5": 1.06, "hr": {"pass_yds": 0.58, "pass_tds": 0.53, "rush_yds": 0.70},
    },
    "young": {
        "name": "Bryce Young", "team": "CAR", "pos": "QB", "num": "9", "tier": 2,
        "pass_yds": 218, "pass_tds": 1.40, "rush_yds": 22, "rush_att": 4.2,
        "completions": 18.4, "attempts": 28.0,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.52, "first_td": 0.14,
        "std": {"pass_yds": 70, "pass_tds": 0.96, "rush_yds": 14, "completions": 4.4, "attempts": 5.2},
        "l5": 0.96, "hr": {"pass_yds": 0.52, "pass_tds": 0.48, "rush_yds": 0.52},
    },
    "levis": {
        "name": "Will Levis", "team": "TEN", "pos": "QB", "num": "8", "tier": 3,
        "pass_yds": 226, "pass_tds": 1.48, "rush_yds": 16, "rush_att": 3.4,
        "completions": 19.2, "attempts": 29.2,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.55, "first_td": 0.15,
        "std": {"pass_yds": 68, "pass_tds": 0.95, "rush_yds": 12, "completions": 4.1, "attempts": 4.9},
        "l5": 0.98, "hr": {"pass_yds": 0.54, "pass_tds": 0.50, "rush_yds": 0.48},
    },
    "minshew": {
        "name": "Gardner Minshew", "team": "LV", "pos": "QB", "num": "15", "tier": 3,
        "pass_yds": 230, "pass_tds": 1.52, "rush_yds": 12, "rush_att": 2.8,
        "completions": 19.6, "attempts": 29.8,
        "rec_yds": 0, "receptions": 0, "rec_tds": 0, "longest_rec": 0,
        "anytime_td": 0.56, "first_td": 0.15,
        "std": {"pass_yds": 68, "pass_tds": 0.95, "rush_yds": 10, "completions": 4.0, "attempts": 4.8},
        "l5": 0.99, "hr": {"pass_yds": 0.55, "pass_tds": 0.51, "rush_yds": 0.46},
    },

    # ── RUNNING BACKS ─────────────────────────────────────────────────────────
    "cmc": {
        "name": "Christian McCaffrey", "team": "SF", "pos": "RB", "num": "23", "tier": 1,
        "rush_yds": 72, "rush_att": 14.8, "rec_yds": 52, "receptions": 6.1,
        "rec_tds": 0.18, "longest_rec": 22, "anytime_td": 0.82, "first_td": 0.26,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 28, "rush_att": 2.8, "rec_yds": 22, "receptions": 2.0},
        "l5": 1.03, "hr": {"rush_yds": 0.62, "rec_yds": 0.68, "rush_att": 0.64},
    },
    "henry": {
        "name": "Derrick Henry", "team": "TEN", "pos": "RB", "num": "22", "tier": 1,
        "rush_yds": 88, "rush_att": 18.2, "rec_yds": 18, "receptions": 2.1,
        "rec_tds": 0.08, "longest_rec": 12, "anytime_td": 0.78, "first_td": 0.24,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 32, "rush_att": 3.2, "rec_yds": 14, "receptions": 1.2},
        "l5": 0.98, "hr": {"rush_yds": 0.65, "rec_yds": 0.50, "rush_att": 0.66},
    },
    "barkley": {
        "name": "Saquon Barkley", "team": "PHI", "pos": "RB", "num": "26", "tier": 1,
        "rush_yds": 82, "rush_att": 16.4, "rec_yds": 38, "receptions": 4.4,
        "rec_tds": 0.14, "longest_rec": 18, "anytime_td": 0.72, "first_td": 0.22,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 30, "rush_att": 3.0, "rec_yds": 18, "receptions": 1.8},
        "l5": 1.01, "hr": {"rush_yds": 0.64, "rec_yds": 0.56, "rush_att": 0.65},
    },
    "taylor": {
        "name": "Jonathan Taylor", "team": "IND", "pos": "RB", "num": "28", "tier": 1,
        "rush_yds": 85, "rush_att": 17.2, "rec_yds": 22, "receptions": 2.8,
        "rec_tds": 0.14, "longest_rec": 14, "anytime_td": 0.76, "first_td": 0.23,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 30, "rush_att": 3.0, "rec_yds": 14, "receptions": 1.4},
        "l5": 1.02, "hr": {"rush_yds": 0.64, "rec_yds": 0.48, "rush_att": 0.66},
    },
    "gibbs": {
        "name": "Jahmyr Gibbs", "team": "DET", "pos": "RB", "num": "26", "tier": 1,
        "rush_yds": 76, "rush_att": 15.4, "rec_yds": 42, "receptions": 4.8,
        "rec_tds": 0.16, "longest_rec": 20, "anytime_td": 0.74, "first_td": 0.22,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 28, "rush_att": 2.8, "rec_yds": 18, "receptions": 1.8},
        "l5": 1.04, "hr": {"rush_yds": 0.63, "rec_yds": 0.60, "rush_att": 0.64},
    },
    "achane": {
        "name": "De'Von Achane", "team": "MIA", "pos": "RB", "num": "28", "tier": 1,
        "rush_yds": 72, "rush_att": 13.6, "rec_yds": 44, "receptions": 5.0,
        "rec_tds": 0.16, "longest_rec": 22, "anytime_td": 0.72, "first_td": 0.22,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 32, "rush_att": 3.2, "rec_yds": 20, "receptions": 2.0},
        "l5": 1.05, "hr": {"rush_yds": 0.61, "rec_yds": 0.62, "rush_att": 0.62},
    },
    "etienne": {
        "name": "Travis Etienne", "team": "JAX", "pos": "RB", "num": "1", "tier": 2,
        "rush_yds": 68, "rush_att": 14.2, "rec_yds": 36, "receptions": 4.2,
        "rec_tds": 0.12, "longest_rec": 18, "anytime_td": 0.62, "first_td": 0.18,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 28, "rush_att": 2.8, "rec_yds": 16, "receptions": 1.6},
        "l5": 1.00, "hr": {"rush_yds": 0.60, "rec_yds": 0.54, "rush_att": 0.62},
    },
    "hall": {
        "name": "Breece Hall", "team": "NYJ", "pos": "RB", "num": "20", "tier": 2,
        "rush_yds": 62, "rush_att": 13.0, "rec_yds": 36, "receptions": 4.2,
        "rec_tds": 0.11, "longest_rec": 16, "anytime_td": 0.60, "first_td": 0.18,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 16, "receptions": 1.6},
        "l5": 0.99, "hr": {"rush_yds": 0.58, "rec_yds": 0.52, "rush_att": 0.60},
    },
    "swift": {
        "name": "D'Andre Swift", "team": "CHI", "pos": "RB", "num": "28", "tier": 2,
        "rush_yds": 64, "rush_att": 13.4, "rec_yds": 38, "receptions": 4.4,
        "rec_tds": 0.12, "longest_rec": 18, "anytime_td": 0.62, "first_td": 0.18,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 18, "receptions": 1.8},
        "l5": 1.00, "hr": {"rush_yds": 0.60, "rec_yds": 0.56, "rush_att": 0.62},
    },
    "mixon": {
        "name": "Joe Mixon", "team": "HOU", "pos": "RB", "num": "28", "tier": 2,
        "rush_yds": 74, "rush_att": 14.8, "rec_yds": 28, "receptions": 3.2,
        "rec_tds": 0.14, "longest_rec": 14, "anytime_td": 0.68, "first_td": 0.20,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 28, "rush_att": 2.8, "rec_yds": 14, "receptions": 1.4},
        "l5": 1.01, "hr": {"rush_yds": 0.62, "rec_yds": 0.48, "rush_att": 0.64},
    },
    "montgomery": {
        "name": "David Montgomery", "team": "DET", "pos": "RB", "num": "5", "tier": 2,
        "rush_yds": 70, "rush_att": 14.2, "rec_yds": 22, "receptions": 2.6,
        "rec_tds": 0.14, "longest_rec": 12, "anytime_td": 0.70, "first_td": 0.21,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 28, "rush_att": 2.8, "rec_yds": 12, "receptions": 1.2},
        "l5": 1.00, "hr": {"rush_yds": 0.62, "rec_yds": 0.46, "rush_att": 0.63},
    },
    "jones_rb": {
        "name": "Aaron Jones", "team": "MIN", "pos": "RB", "num": "33", "tier": 2,
        "rush_yds": 60, "rush_att": 12.6, "rec_yds": 34, "receptions": 4.0,
        "rec_tds": 0.11, "longest_rec": 16, "anytime_td": 0.58, "first_td": 0.17,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 16, "receptions": 1.6},
        "l5": 0.99, "hr": {"rush_yds": 0.58, "rec_yds": 0.52, "rush_att": 0.60},
    },
    "jacobs": {
        "name": "Josh Jacobs", "team": "GB", "pos": "RB", "num": "8", "tier": 2,
        "rush_yds": 62, "rush_att": 13.2, "rec_yds": 32, "receptions": 3.8,
        "rec_tds": 0.12, "longest_rec": 16, "anytime_td": 0.60, "first_td": 0.18,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 16, "receptions": 1.6},
        "l5": 1.00, "hr": {"rush_yds": 0.59, "rec_yds": 0.52, "rush_att": 0.61},
    },
    "kamara": {
        "name": "Alvin Kamara", "team": "NO", "pos": "RB", "num": "41", "tier": 2,
        "rush_yds": 62, "rush_att": 12.8, "rec_yds": 40, "receptions": 4.6,
        "rec_tds": 0.13, "longest_rec": 18, "anytime_td": 0.62, "first_td": 0.19,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 18, "receptions": 1.8},
        "l5": 1.00, "hr": {"rush_yds": 0.59, "rec_yds": 0.58, "rush_att": 0.61},
    },
    "robinson": {
        "name": "Brian Robinson Jr", "team": "WAS", "pos": "RB", "num": "8", "tier": 2,
        "rush_yds": 66, "rush_att": 13.8, "rec_yds": 22, "receptions": 2.6,
        "rec_tds": 0.12, "longest_rec": 12, "anytime_td": 0.62, "first_td": 0.18,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 12, "receptions": 1.2},
        "l5": 1.01, "hr": {"rush_yds": 0.60, "rec_yds": 0.46, "rush_att": 0.62},
    },
    "williams_rb": {
        "name": "Javonte Williams", "team": "DEN", "pos": "RB", "num": "33", "tier": 2,
        "rush_yds": 60, "rush_att": 12.6, "rec_yds": 24, "receptions": 2.8,
        "rec_tds": 0.10, "longest_rec": 12, "anytime_td": 0.56, "first_td": 0.16,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "std": {"rush_yds": 26, "rush_att": 2.6, "rec_yds": 12, "receptions": 1.2},
        "l5": 0.99, "hr": {"rush_yds": 0.57, "rec_yds": 0.46, "rush_att": 0.59},
    },

    # ── WIDE RECEIVERS ────────────────────────────────────────────────────────
    "hill": {
        "name": "Tyreek Hill", "team": "MIA", "pos": "WR", "num": "10", "tier": 1,
        "rec_yds": 82, "receptions": 6.8, "rec_tds": 0.46, "longest_rec": 38,
        "rush_yds": 4, "rush_att": 0.6,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.62, "first_td": 0.19,
        "std": {"rec_yds": 30, "receptions": 2.2, "rush_yds": 6},
        "l5": 1.02, "hr": {"rec_yds": 0.65, "receptions": 0.63, "rec_tds": 0.42},
    },
    "jefferson": {
        "name": "Justin Jefferson", "team": "MIN", "pos": "WR", "num": "18", "tier": 1,
        "rec_yds": 76, "receptions": 5.9, "rec_tds": 0.42, "longest_rec": 34,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.54, "first_td": 0.16,
        "std": {"rec_yds": 28, "receptions": 2.0, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.64, "receptions": 0.62, "rec_tds": 0.40},
    },
    "chase": {
        "name": "Ja'Marr Chase", "team": "CIN", "pos": "WR", "num": "1", "tier": 1,
        "rec_yds": 79, "receptions": 6.1, "rec_tds": 0.48, "longest_rec": 36,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.58, "first_td": 0.18,
        "std": {"rec_yds": 29, "receptions": 2.1, "rush_yds": 0},
        "l5": 1.04, "hr": {"rec_yds": 0.66, "receptions": 0.64, "rec_tds": 0.42},
    },
    "lamb": {
        "name": "CeeDee Lamb", "team": "DAL", "pos": "WR", "num": "88", "tier": 1,
        "rec_yds": 84, "receptions": 7.0, "rec_tds": 0.48, "longest_rec": 38,
        "rush_yds": 2, "rush_att": 0.4,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.64, "first_td": 0.20,
        "std": {"rec_yds": 32, "receptions": 2.4, "rush_yds": 4},
        "l5": 1.01, "hr": {"rec_yds": 0.68, "receptions": 0.68, "rec_tds": 0.43},
    },
    "brown": {
        "name": "AJ Brown", "team": "PHI", "pos": "WR", "num": "11", "tier": 1,
        "rec_yds": 78, "receptions": 5.8, "rec_tds": 0.46, "longest_rec": 36,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.60, "first_td": 0.18,
        "std": {"rec_yds": 30, "receptions": 2.2, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.65, "receptions": 0.61, "rec_tds": 0.42},
    },
    "diggs": {
        "name": "Stefon Diggs", "team": "HOU", "pos": "WR", "num": "11", "tier": 1,
        "rec_yds": 72, "receptions": 5.9, "rec_tds": 0.40, "longest_rec": 32,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.55, "first_td": 0.16,
        "std": {"rec_yds": 28, "receptions": 2.0, "rush_yds": 0},
        "l5": 0.97, "hr": {"rec_yds": 0.63, "receptions": 0.62, "rec_tds": 0.39},
    },
    "adams": {
        "name": "Davante Adams", "team": "LV", "pos": "WR", "num": "17", "tier": 1,
        "rec_yds": 74, "receptions": 6.2, "rec_tds": 0.42, "longest_rec": 30,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.56, "first_td": 0.17,
        "std": {"rec_yds": 28, "receptions": 2.2, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.63, "receptions": 0.63, "rec_tds": 0.40},
    },
    "metcalf": {
        "name": "DK Metcalf", "team": "SEA", "pos": "WR", "num": "14", "tier": 1,
        "rec_yds": 72, "receptions": 5.4, "rec_tds": 0.44, "longest_rec": 36,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.58, "first_td": 0.18,
        "std": {"rec_yds": 30, "receptions": 2.2, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.62, "receptions": 0.59, "rec_tds": 0.40},
    },
    "waddle": {
        "name": "Jaylen Waddle", "team": "MIA", "pos": "WR", "num": "17", "tier": 1,
        "rec_yds": 70, "receptions": 6.2, "rec_tds": 0.38, "longest_rec": 30,
        "rush_yds": 2, "rush_att": 0.3,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.52, "first_td": 0.15,
        "std": {"rec_yds": 28, "receptions": 2.2, "rush_yds": 4},
        "l5": 1.02, "hr": {"rec_yds": 0.62, "receptions": 0.63, "rec_tds": 0.37},
    },
    "amon": {
        "name": "Amon-Ra St. Brown", "team": "DET", "pos": "WR", "num": "14", "tier": 1,
        "rec_yds": 74, "receptions": 6.8, "rec_tds": 0.44, "longest_rec": 30,
        "rush_yds": 0, "rush_att": 0.2,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.58, "first_td": 0.17,
        "std": {"rec_yds": 26, "receptions": 2.0, "rush_yds": 0},
        "l5": 1.03, "hr": {"rec_yds": 0.65, "receptions": 0.67, "rec_tds": 0.40},
    },
    "kupp": {
        "name": "Cooper Kupp", "team": "LAR", "pos": "WR", "num": "10", "tier": 1,
        "rec_yds": 68, "receptions": 5.8, "rec_tds": 0.38, "longest_rec": 28,
        "rush_yds": 0, "rush_att": 0.2,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.50, "first_td": 0.15,
        "std": {"rec_yds": 26, "receptions": 2.1, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.62, "receptions": 0.61, "rec_tds": 0.38},
    },
    "evans": {
        "name": "Mike Evans", "team": "TB", "pos": "WR", "num": "13", "tier": 1,
        "rec_yds": 70, "receptions": 5.2, "rec_tds": 0.48, "longest_rec": 34,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.62, "first_td": 0.19,
        "std": {"rec_yds": 28, "receptions": 2.2, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.62, "receptions": 0.58, "rec_tds": 0.42},
    },
    "nabers": {
        "name": "Malik Nabers", "team": "NYG", "pos": "WR", "num": "9", "tier": 1,
        "rec_yds": 70, "receptions": 5.8, "rec_tds": 0.40, "longest_rec": 32,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.54, "first_td": 0.16,
        "std": {"rec_yds": 28, "receptions": 2.2, "rush_yds": 0},
        "l5": 1.04, "hr": {"rec_yds": 0.63, "receptions": 0.62, "rec_tds": 0.38},
    },
    "garrett": {
        "name": "Garrett Wilson", "team": "NYJ", "pos": "WR", "num": "17", "tier": 1,
        "rec_yds": 68, "receptions": 5.8, "rec_tds": 0.38, "longest_rec": 30,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.52, "first_td": 0.15,
        "std": {"rec_yds": 28, "receptions": 2.2, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.62, "receptions": 0.62, "rec_tds": 0.37},
    },
    "pickens": {
        "name": "George Pickens", "team": "PIT", "pos": "WR", "num": "14", "tier": 2,
        "rec_yds": 60, "receptions": 4.6, "rec_tds": 0.36, "longest_rec": 28,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.48, "first_td": 0.14,
        "std": {"rec_yds": 26, "receptions": 2.0, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.58, "receptions": 0.57, "rec_tds": 0.35},
    },
    "mclaurin": {
        "name": "Terry McLaurin", "team": "WAS", "pos": "WR", "num": "17", "tier": 2,
        "rec_yds": 68, "receptions": 5.4, "rec_tds": 0.40, "longest_rec": 30,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.52, "first_td": 0.16,
        "std": {"rec_yds": 28, "receptions": 2.0, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.62, "receptions": 0.60, "rec_tds": 0.38},
    },
    "deebo": {
        "name": "Deebo Samuel", "team": "SF", "pos": "WR", "num": "19", "tier": 2,
        "rec_yds": 58, "receptions": 4.8, "rec_tds": 0.36, "longest_rec": 26,
        "rush_yds": 16, "rush_att": 3.2,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.52, "first_td": 0.16,
        "std": {"rec_yds": 24, "receptions": 1.8, "rush_yds": 12},
        "l5": 0.98, "hr": {"rec_yds": 0.58, "receptions": 0.58, "rec_tds": 0.36},
    },
    "aiyuk": {
        "name": "Brandon Aiyuk", "team": "SF", "pos": "WR", "num": "11", "tier": 2,
        "rec_yds": 66, "receptions": 5.2, "rec_tds": 0.40, "longest_rec": 30,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.54, "first_td": 0.16,
        "std": {"rec_yds": 26, "receptions": 2.0, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.62, "receptions": 0.60, "rec_tds": 0.38},
    },
    "moore": {
        "name": "DJ Moore", "team": "CHI", "pos": "WR", "num": "2", "tier": 2,
        "rec_yds": 64, "receptions": 5.4, "rec_tds": 0.36, "longest_rec": 28,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.48, "first_td": 0.14,
        "std": {"rec_yds": 26, "receptions": 2.0, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.60, "receptions": 0.60, "rec_tds": 0.36},
    },
    "flowers": {
        "name": "Zay Flowers", "team": "BAL", "pos": "WR", "num": "4", "tier": 2,
        "rec_yds": 62, "receptions": 5.0, "rec_tds": 0.36, "longest_rec": 28,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.48, "first_td": 0.14,
        "std": {"rec_yds": 24, "receptions": 1.8, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.60, "receptions": 0.59, "rec_tds": 0.36},
    },
    "godwin": {
        "name": "Chris Godwin", "team": "TB", "pos": "WR", "num": "14", "tier": 2,
        "rec_yds": 62, "receptions": 5.8, "rec_tds": 0.36, "longest_rec": 26,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.48, "first_td": 0.14,
        "std": {"rec_yds": 24, "receptions": 2.0, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.60, "receptions": 0.61, "rec_tds": 0.36},
    },
    "pittman": {
        "name": "Michael Pittman Jr", "team": "IND", "pos": "WR", "num": "11", "tier": 2,
        "rec_yds": 60, "receptions": 5.0, "rec_tds": 0.34, "longest_rec": 24,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.46, "first_td": 0.14,
        "std": {"rec_yds": 24, "receptions": 2.0, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.59, "receptions": 0.59, "rec_tds": 0.34},
    },
    "odunze": {
        "name": "Rome Odunze", "team": "CHI", "pos": "WR", "num": "15", "tier": 2,
        "rec_yds": 58, "receptions": 4.8, "rec_tds": 0.32, "longest_rec": 26,
        "rush_yds": 0, "rush_att": 0.1,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.46, "first_td": 0.14,
        "std": {"rec_yds": 24, "receptions": 1.8, "rush_yds": 0},
        "l5": 1.02, "hr": {"rec_yds": 0.58, "receptions": 0.58, "rec_tds": 0.34},
    },

    # ── TIGHT ENDS ────────────────────────────────────────────────────────────
    "kelce": {
        "name": "Travis Kelce", "team": "KC", "pos": "TE", "num": "87", "tier": 1,
        "rec_yds": 64, "receptions": 5.8, "rec_tds": 0.40, "longest_rec": 28,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.52, "first_td": 0.15,
        "std": {"rec_yds": 24, "receptions": 2.0, "rush_yds": 0},
        "l5": 0.98, "hr": {"rec_yds": 0.62, "receptions": 0.63, "rec_tds": 0.38},
    },
    "andrews": {
        "name": "Mark Andrews", "team": "BAL", "pos": "TE", "num": "89", "tier": 1,
        "rec_yds": 58, "receptions": 5.2, "rec_tds": 0.38, "longest_rec": 24,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.48, "first_td": 0.14,
        "std": {"rec_yds": 22, "receptions": 1.8, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.60, "receptions": 0.61, "rec_tds": 0.37},
    },
    "kittle": {
        "name": "George Kittle", "team": "SF", "pos": "TE", "num": "85", "tier": 1,
        "rec_yds": 60, "receptions": 5.4, "rec_tds": 0.40, "longest_rec": 26,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.50, "first_td": 0.15,
        "std": {"rec_yds": 23, "receptions": 1.9, "rush_yds": 0},
        "l5": 1.02, "hr": {"rec_yds": 0.61, "receptions": 0.62, "rec_tds": 0.38},
    },
    "goedert": {
        "name": "Dallas Goedert", "team": "PHI", "pos": "TE", "num": "88", "tier": 1,
        "rec_yds": 58, "receptions": 5.0, "rec_tds": 0.38, "longest_rec": 24,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.48, "first_td": 0.14,
        "std": {"rec_yds": 22, "receptions": 1.8, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.60, "receptions": 0.60, "rec_tds": 0.37},
    },
    "pitts": {
        "name": "Kyle Pitts", "team": "ATL", "pos": "TE", "num": "8", "tier": 2,
        "rec_yds": 52, "receptions": 4.6, "rec_tds": 0.28, "longest_rec": 22,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.38, "first_td": 0.11,
        "std": {"rec_yds": 22, "receptions": 1.8, "rush_yds": 0},
        "l5": 0.98, "hr": {"rec_yds": 0.56, "receptions": 0.57, "rec_tds": 0.30},
    },
    "engram": {
        "name": "Evan Engram", "team": "JAX", "pos": "TE", "num": "17", "tier": 2,
        "rec_yds": 52, "receptions": 5.2, "rec_tds": 0.30, "longest_rec": 22,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.40, "first_td": 0.12,
        "std": {"rec_yds": 20, "receptions": 1.8, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.57, "receptions": 0.62, "rec_tds": 0.32},
    },
    "mcbride": {
        "name": "Trey McBride", "team": "ARI", "pos": "TE", "num": "85", "tier": 2,
        "rec_yds": 54, "receptions": 5.0, "rec_tds": 0.32, "longest_rec": 22,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.42, "first_td": 0.12,
        "std": {"rec_yds": 20, "receptions": 1.8, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.58, "receptions": 0.60, "rec_tds": 0.33},
    },
    "njoku": {
        "name": "David Njoku", "team": "CLE", "pos": "TE", "num": "85", "tier": 2,
        "rec_yds": 50, "receptions": 4.6, "rec_tds": 0.30, "longest_rec": 20,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.40, "first_td": 0.12,
        "std": {"rec_yds": 20, "receptions": 1.8, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.56, "receptions": 0.57, "rec_tds": 0.32},
    },
    "freiermuth": {
        "name": "Pat Freiermuth", "team": "PIT", "pos": "TE", "num": "88", "tier": 2,
        "rec_yds": 46, "receptions": 4.2, "rec_tds": 0.28, "longest_rec": 18,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.38, "first_td": 0.11,
        "std": {"rec_yds": 18, "receptions": 1.6, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.55, "receptions": 0.56, "rec_tds": 0.30},
    },
    "kmet": {
        "name": "Cole Kmet", "team": "CHI", "pos": "TE", "num": "85", "tier": 2,
        "rec_yds": 44, "receptions": 4.0, "rec_tds": 0.26, "longest_rec": 18,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.36, "first_td": 0.10,
        "std": {"rec_yds": 18, "receptions": 1.6, "rush_yds": 0},
        "l5": 1.00, "hr": {"rec_yds": 0.54, "receptions": 0.55, "rec_tds": 0.29},
    },
    "ferguson": {
        "name": "Jake Ferguson", "team": "DAL", "pos": "TE", "num": "87", "tier": 2,
        "rec_yds": 50, "receptions": 4.6, "rec_tds": 0.32, "longest_rec": 22,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.42, "first_td": 0.12,
        "std": {"rec_yds": 20, "receptions": 1.8, "rush_yds": 0},
        "l5": 0.99, "hr": {"rec_yds": 0.57, "receptions": 0.58, "rec_tds": 0.33},
    },
    "likely": {
        "name": "Isaiah Likely", "team": "BAL", "pos": "TE", "num": "80", "tier": 2,
        "rec_yds": 46, "receptions": 4.2, "rec_tds": 0.28, "longest_rec": 20,
        "rush_yds": 0, "rush_att": 0,
        "pass_yds": 0, "pass_tds": 0, "completions": 0, "attempts": 0,
        "anytime_td": 0.38, "first_td": 0.11,
        "std": {"rec_yds": 18, "receptions": 1.6, "rush_yds": 0},
        "l5": 1.01, "hr": {"rec_yds": 0.55, "receptions": 0.56, "rec_tds": 0.30},
    },
}
